name: ride-service pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

jobs:
  build:
    environment: Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for build.sh
        run: ./build.sh